Repository aws/aws-cdk-rfcs, pull requests merged in 2023-10, with the labels that each got.

#545 Update RFC table in README
  README.md
Labels: auto-approve

#546 Update RFC table in README
  README.md
Labels: auto-approve

#547 Update RFC table in README
  README.md
Labels: auto-approve

#550 Update RFC table in README
  README.md
Labels: auto-approve

#553 Update RFC table in README
  ACCEPTED.md
  CLOSED.md
  FULL_INDEX.md
  PROPOSED.md
  README.md
Labels: auto-approve

#554 Update RFC table in README
  FULL_INDEX.md
  PROPOSED.md
  README.md
Labels: auto-approve

#555 Update RFC table in README
  ACCEPTED.md
  FULL_INDEX.md
  PROPOSED.md
  README.md
Labels: auto-approve

#488 RFC 473: EventBridge Pipes L2 Construct
  text/0473-eventbridge-pipes.md
Labels: l2-request

#506 RFC502: L2 Constructs for vpclattice
  .gitignore
  text/0502_aws-vpclattice.md
Labels: status/final-comment-period, status/api-approved, l2-request

#556 Update RFC table in README
  ACCEPTED.md
  FULL_INDEX.md
  PROPOSED.md
  README.md
Labels: auto-approve

#557 Update RFC table in README
  ACCEPTED.md
  FULL_INDEX.md
  README.md
Labels: auto-approve

#558 Update RFC table in README
  FULL_INDEX.md
  PROPOSED.md
  README.md
Labels: auto-approve

#559 Update RFC table in README
  CLOSED.md
  FULL_INDEX.md
  PROPOSED.md
Labels: auto-approve

#560 Update RFC table in README
  CLOSED.md
  FULL_INDEX.md
  PROPOSED.md
Labels: auto-approve

#561 Update RFC table in README
  CLOSED.md
  FULL_INDEX.md
  PROPOSED.md
Labels: auto-approve

#562 Update RFC table in README
  ACCEPTED.md
  FULL_INDEX.md
  PROPOSED.md
Labels: auto-approve

#563 Update RFC table in README
  ACCEPTED.md
  CLOSED.md
  FULL_INDEX.md
  PROPOSED.md
Labels: auto-approve

#564 Update RFC table in README
  CLOSED.md
  FULL_INDEX.md
  PROPOSED.md
Labels: auto-approve

#565 Update RFC table in README
  CLOSED.md
  FULL_INDEX.md
  PROPOSED.md
Labels: auto-approve

#566 Update RFC table in README
  CLOSED.md
  FULL_INDEX.md
  PROPOSED.md
Labels: auto-approve

#567 Update RFC table in README
  CLOSED.md
  FULL_INDEX.md
  PROPOSED.md
Labels: auto-approve

#568 Update RFC table in README
  CLOSED.md
  FULL_INDEX.md
  PROPOSED.md
Labels: auto-approve

#569 Update RFC table in README
  CLOSED.md
  FULL_INDEX.md
  PROPOSED.md
Labels: auto-approve

#570 Update RFC table in README
  CLOSED.md
  FULL_INDEX.md
  PROPOSED.md
Labels: auto-approve

#571 Update RFC table in README
  CLOSED.md
  FULL_INDEX.md
  PROPOSED.md
Labels: auto-approve

#572 Update RFC table in README
  CLOSED.md
  FULL_INDEX.md
  PROPOSED.md
Labels: auto-approve

#573 Update RFC table in README
  CLOSED.md
  FULL_INDEX.md
  PROPOSED.md
Labels: auto-approve

#574 Update RFC table in README
  CLOSED.md
  FULL_INDEX.md
  PROPOSED.md
Labels: auto-approve
